"""email verification and pending registrations

Revision ID: 32bababc3bd5
Revises: c9799a70ac81
Create Date: 2026-08-29 22:46:27.537287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# 自訂型別（UtcDateTime）在 autogenerate 產生的欄位定義裡會用完整路徑引用
import app.db.base


# revision identifiers, used by Alembic.
revision: str = '32bababc3bd5'
down_revision: Union[str, None] = 'c9799a70ac81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_registrations',
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('send_count', sa.Integer(), nullable=False),
    sa.Column('last_sent_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', app.db.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_registrations', schema=None) as batch_op:
        batch_op.create_index('ix_pending_email', ['email'], unique=False)
        batch_op.create_index('ix_pending_expires', ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_registrations_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index('ix_pending_username', ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_registrations', schema=None) as batch_op:
        batch_op.drop_index('ix_pending_username')
        batch_op.drop_index(batch_op.f('ix_pending_registrations_token_hash'))
        batch_op.drop_index('ix_pending_expires')
        batch_op.drop_index('ix_pending_email')

    op.drop_table('pending_registrations')
    # ### end Alembic commands ###
