"""password reset tickets

Revision ID: 8c97ca614fbf
Revises: 32bababc3bd5
Create Date: 2026-08-29 23:03:45.400363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# 自訂型別（UtcDateTime）在 autogenerate 產生的欄位定義裡會用完整路徑引用
import app.db.base


# revision identifiers, used by Alembic.
revision: str = '8c97ca614fbf'
down_revision: Union[str, None] = '32bababc3bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_resets',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('last_sent_at', app.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', app.db.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UtcDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_resets_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index('ix_reset_expires', ['expires_at'], unique=False)
        batch_op.create_index('ix_reset_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_index('ix_reset_user')
        batch_op.drop_index('ix_reset_expires')
        batch_op.drop_index(batch_op.f('ix_password_resets_token_hash'))

    op.drop_table('password_resets')
    # ### end Alembic commands ###
